server {
    listen 80;

    # Statische Dateien
    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }

    # API-Anfragen an den Backend-Container weiterleiten
    location /health       { proxy_pass http://backend:8000; }
    location /empfehlungen { proxy_pass http://backend:8000; }
    location /statistik    { proxy_pass http://backend:8000; }
    location /kurse        { proxy_pass http://backend:8000; }
}
